#!/usr/bin/with-contenv bash
# shellcheck shell=bash

if [ ! -z $TEST_PROXY ];
then
    status=0
    while [ $status -ne 1 ]
    do
        case "$(curl -x http://pyload-openvpn:8080 -s --max-time 2 -I $TEST_PROXY | sed 's/^[^ ]*  *\([0-9]\).*/\1/; 1q')" in
        [23]) status=1;;
        5) echo "The web proxy won't let us through";;
        *) echo "The network is down or very slow";;
        esac
        sleep 2s
    done
fi
PORT=$(sed -n -e '/webui/,/proxy/p' /config/settings/pyload.cfg | grep "Port" | awk -F '=' '{print $2}' | tr -d ' ')

exec \
    s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost ${PORT:-8000}" \
    s6-setuidgid abc pyload --userdir /config --storagedir /downloads
